package deep_pills.model.enums.types;

public enum EMailType {
    PSWD_RECOVERY,
    APPOINT_SCHEDULED,
    APPOINT_CANCELLED,
    APPOINT_RESCHEDULED,
    APPOINT_SERVED,
    MEMB_ACQUIRED,
    MEMB_RESIGNED,
    MEMB_PATIENT_ADDED,
    MEMB_PATIENT_REMOVED,
    MEMB_STATE_UPDATED,
    MEMB_CHARGE,
    MEMB_PAYMENT,
    ACCOUNT_STATE_UPDATED,
    REGISTRATION,
    FREE_DAY,
    CLAIM
}
